name: Build Web Container

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      image_name: web
      context: web
      target: dodn-web
