name: Build API Container

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      image_name: api
      context: api
      target: dodn-api
